config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  api_version(:module => "api/v1/customer", :header => {:name => "Accept", :value => "application/centarium.com; version=1"}) do
    resources :users do
      collection do
        post :sign_up
        get :generate_code
        post :login
        post :verify_otp
        post :resend_otp
        post :logout
        get :view_profile
        post :update_profile
        post :send_otp_mobile
        post :otp_change_mobile
        post :upload_doc
        post :forgot_password
        post :update_password
      end
    end    
    resources :stores do
      collection do
        post :store_detail
        post :add_fav
      end
    end
    resources :products do
      collection do
        post :product_list
        post :product_detail
        post :product_review
        post :write_review
        post :add_fav
      end
    end
    resources :socials do
      collection do
        post :social_login
      end
    end
    resources :static_contents  do
      collection do
        post :static_content 
        post :contact_us   
      end
    end
    resources :notifications do
      collection do
        post :notification_list
        post :delete_notification
      end
    end
    namespace :storeapi do
      resources :stores do
        collection do
          post :sign_up
          get :generate_code
          post :login
          post :verify_otp
          post :resend_otp
          post :logout
          get :view_profile
          post :update_profile
          post :send_otp_email
          post :otp_change_email
          post :upload_doc
          post :send_otp_mobile
          post :otp_change_mobile
          post :forgot_password
          post :update_password
        end
      end
      resources :products do
        collection do
          post :product_update
          post :product_detail
          post :product_list
          post :product_review
        end
      end
      resources :campaigns do
        collection do
          get :product_list_name
          post :edit_campaign
          post :list_campaign
          post :detail_campaign
        end
      end
    end
  end
  namespace :admin do
    root :to => "home#index"
    resources :sessions
    resources :home do
      collection do
        get :forget_password
        patch :reset_password
      end
    end
    resources :admin_users do
      collection do
        post :user_status
      end
      member do
        get :change_password
        post :update_password
      end
    end
    resources :users do
      collection do
        get :user_status
        get :user_approve
      end
    end
    resources :stores do
      collection do
        post :store_status
        get :store_approve
        post :import
        post :export
      end
    end
    resources :products do
     collection do
        post :product_status
     end
    end
    resources :distance do
      collection do
        post :save_distance
      end
    end
    resources :static_pages
    resources :faqs    
    resources :contact_us
    resources :tokens
    get '/login' => 'sessions#new'
  end
  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/store.rb
class Store
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps
  include ActiveModel::SecurePassword
  include Geocoder::Model::Mongoid

  has_secure_password validations: false
  geocoded_by :coordinates
  # after_validation :geocode, :if => :location_changed?
  
  index({ coordinates: "2d" },  { min: -180, max: 180 })



  field :name, type: String
  field :store_type, type: Integer# 0:cloths 1:food and beverages 2:entertainment 3:events 5:gadgets
  field :email, type: String, default: ''
  field :password_digest, :type => String
  field :website, type: String
  field :code, type: String
  field :mobile, type: String, default: ''
  field :address, type: String
  field :country, type: String
  field :city, type: String
  field :location, type: String
  field :coordinates, :type => Array
  field :description, type: String
  field :unique_id, type: String, default: ''
  field :touch_id, type: Mongoid::Boolean, default: false
  field :otp, type: String
  field :otp_gen_time, type: DateTime
  field :access_token, type: String, default: ''
  field :status, type: Integer, default: 1 # 0:Dect by admin 1:Active
  field :admin_approved, type: Integer, default: 0 # 0:rejected 1:Approved
  field :is_verified, type: Mongoid::Boolean, default: false

  has_many :products, dependent: :destroy
  has_many :images, as: :imageable, class_name: "Image"
  has_many :devices, dependent: :destroy
  has_many :ratings, dependent: :destroy, class_name: "StoreRating"
  has_many :fav_stores, dependent: :destroy
  has_many :service_timings, dependent: :destroy
  has_many :user_docs, dependent: :destroy
  has_many :campaigns, dependent: :destroy
  has_many :contact_u, dependent: :destroy
  accepts_nested_attributes_for :service_timings , :allow_destroy => true, :reject_if =>:all_blank
  
  def self.generate_otp_and_send store
    otp = rand(1111..9999)
    store.update_attributes(otp: otp, otp_gen_time: DateTime.current)
    msg = "#{otp} is your one time password(OTP). This is usable once & valid for 15 minuts from request. Do not share with anyone."
    UserMailer.send_otp(store, msg).deliver_now
  end

  def self.forgot_generate_otp_and_send mobile, code, store
    mobile_no = code + mobile
    otp = [*1000..9999].sample
    # otp =  "1234"
    store.update_attributes(otp: otp, otp_gen_time: DateTime.current)
    # TwilioSms.send_otp(mobile_no, "Your Centrium App account OTP is: #{@otp}" )
  end

  def otp_expired?
    otp_gen_time > 15.minutes.ago
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Store.create! row.to_hash      
    end    
  end

  def self.export(options = {})
    headers = ['name','address','description','website','mobile','code']  
    dummy = ['Lalit','Delhi','Mobiloitte Technologies','www.mobiloitte.com','9876543210','+91']  
    CSV.generate(options) do |csv|
      csv << headers
      csv << dummy
    end
  end

  # def self.at_range(latitude, longitude, range)
  #   geo_near([latitude, longitude]).max_distance(range.fdiv(111.12))
  # end

  # def latitude
  #   coordinates[0]
  # end

  # def longitude
  #   coordinates[1]
  # end
end

app/controllers/admin/stores_controller.rb
require 'will_paginate/array'
class Admin::StoresController < ApplicationController
  before_action :require_admin_user
  before_action :find_store, except: [:index, :vendor_list, :new, :create, :import, :export]

  def index
    if params[:search].present? && params[:status].present?
      @search = Store.any_of({name: Regexp.new(".*#{params[:search]}.*","i")},{email: Regexp.new(".*#{params[:search]}.*","i")},{mobile: Regexp.new(".*#{params[:search]}.*","i")}).where(status: params[:status])
    elsif params[:search].present? && !params[:status].present? 
      @search = Store.any_of({name: Regexp.new(".*#{params[:search]}.*","i")},{email: Regexp.new(".*#{params[:search]}.*","i")},{mobile: Regexp.new(".*#{params[:search]}.*","i")}).where(status: (0..1))
    elsif !params[:search].present? && params[:status].present? 
      @search = Store.where(status: params[:status])
    else
      @search = Store.where(status: (0..1))
    end          
    @stores = @search.order("created_at desc").paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @store = Store.new
  end

  def create
    @store  = Store.new(store_params)
    if @store.save
       flash[:notice] = "Store created successfully."
       redirect_to admin_stores_path 
    else   
       flash[:alert] = @store.errors.messages
       redirect_to request.referer

    end 
  end

  def store_status
   if @store.status.eql?(0) 
      @store.update_attributes(status: 1)
      redirect_to  admin_stores_path,notice: "Service Provider activated successfully."
   elsif @store.status.eql?(1) 
      @store.update_attributes(status: 0)
      redirect_to  admin_stores_path, notice: "Service Provider blocked successfully."
   end
  end

  def store_approve
    @store.update_attributes(admin_approved: 1) if params[:admin_approved] == "1"
    @store.update_attributes(admin_approved: 0) if params[:admin_approved] == "0"
    redirect_to request.referer
  end

  def edit
  end

  def update
    if @store.update_attributes(store_params)
      redirect_to admin_stores_path, notice: "Provider's profile updated successfully."
    else
      flash[:error] = @store.errors.full_messages.first
      render :edit
    end
  end

  def show
    
  end

  def destroy
    if @store.destroy
      redirect_to  admin_stores_path
    else
      flash[:error] = @store.errors.full_messages.first
      redirect_to  admin_stores_path
    end
  end

  def import
    Store.import(params[:file])
    redirect_to request.referer, notice: "Service Provider List imported."
  end

  def export
    @store = Store.all
    respond_to do |format|
      format.html
      format.csv{ send_data @store.export,filename: "store-dummy-csv.csv"}
    end
  end


  private
  def find_store
    @store = Store.find_by(id: params[:id])
    redirect_to admin_stores_path unless @store
  end

  def store_params
		params.require(:store).permit(:email,:password,:name,:mobile,:address,:status,:gender, :country, :city, :code, :website, :description, :location, :store_type)
	end
end

app/controllers/api/v1/customer/stores_controller.rb
class Api::V1::Customer::StoresController < ApplicationController
	before_action :find_user

  def index
    store_name = Regexp.new(".*#{params[:search]}.*","i")
	location = eval(params[:coordinates])
	if params[:search].present?
	  @stores = Store.where(store_type: params[:store_type]).any_of({:name => store_name}) 
	else
	  @stores = Store.where(store_type: params[:store_type])
	end
	@stores = @stores.geo_near(location).max_distance(10)
	@stores = @stores.map{|x| x.attributes.merge(rating: (x.ratings.pluck(:rate).map(&:to_i).sum > 0) ? ((x.ratings.pluck(:rate).map(&:to_i).sum.to_f)/(x.ratings.count)) : 0, is_fav: (x.fav_stores.find_by(user_id: @current_user.id).eql?(nil) ? false : true), camaign: x.campaigns.try(:last), image: (x.images.first.try(:file_url) if x.images.first.present?))}
	return render :json =>  {responseCode: 200, responseMessage: "Stored fetched successfully.", stores: @stores}
  end

  def store_detail
  	@store = Store.and({:id => params[:id]}, {:store_type => params[:store_type]}).first
  	return render_message 402, "Store doesn't exists." unless @store.present?
  	rating = @store.products.map{|prod| prod.product_ratings.pluck(:rate)}.try(:flatten).try(:sum)/@store.products.map{|prod| prod.product_ratings.size}.try(:flatten).try(:sum)
    @image = @store.try(:images).map{|x| x.try(:file_url)}
    @select = @store.as_json.merge("image" => @image, "service_timing" => @store.try(:service_timings), "rating" => rating).except("otp", "otp_gen_time", "unique_id", "password_digest")
    render json: {responseCode: 200, responseMessage: "Store fetched successfully.",user: @select}
  end

  def add_fav
	@store = Store.find_by({:id => params[:id]})
  	return render_message 402, "Store doesn't exists." unless @store.present?
	@fav_store = @store.fav_stores.find_or_create_by(store_id: params[:id], user_id: @current_user.id)
	if @fav_store.update(is_liked: params[:is_liked])
	  render :json => { :responseCode => 200,
	                  :responseMessage => "Store favorite status updated successfully.",
	                  :fav_store => @fav_store
	                 }
	else
	  render_message 402, "Store favorite status not updated."
    end 
  end
end

app/controllers/api/v1/store/stores_controller.rb
class Api::V1::Store::StoresController < ApplicationController
   before_action :find_store, :only=>[:logout, :view_profile, :update_profile, :send_otp_mobile, :otp_change_mobile, :send_otp_mobile, :upload_doc]

  def sign_up
    @store = Store.any_of({:unique_id => params[:unique_id]},{:email => params[:email].try(:downcase)}, {:phone => params[:mobile]})
    return render_message 402, "Store already exist." if @store.present?
    @store = Store.new(store_params)
    if @store.save
      if params[:image].present?
        @store.images.create(file: params[:image])
      end
      @store.try(:images).try(:reload)
  	  token = User.generate_token
      @store.update_attributes(access_token: token, status: 2)
      @image = @store.try(:images).map{|x| x.try(:file_url)}
      @select = @store.as_json.merge("image" => @image).except("otp", "otp_gen_time", "unique_id", "password_digest")
      Store.generate_otp_and_send(@store)
  	  return render :json =>  {:responseCode => 200, :responseMessage => "Signup successfully.", store: @select}
    else
      return render_message 402, @store.errors.full_messages.first
    end
  end	

  def verify_otp
    @store = Store.find_by(mobile: params[:mobile])
    return render_message 402, "Store doesn't exist." unless @store.present?
    if @store.otp == params[:otp]
      if @store.otp_expired?
        return render_message 402, "OTP is expired."
      else
        @store.update_attributes(otp: nil, status: 1)
        @image = @store.try(:images).map{|x| x.try(:file_url)}
        @select = @store.as_json.merge("image" => @image).except("otp", "otp_gen_time", "unique_id", "password_digest")
        device = @store.devices.create(device_params) 
        render :json =>  {:responseCode => 200, :responseMessage => "Otp verified successfully.", :store => @select }
      end
    else
      return render_message 402, "OTP is not valid."
    end
  end

  def login
  	if params[:type] == "seed"
  	  @store = Store.find_by(unique_id: params[:unique_id])
  	  return render_message 402, "Store doesn't exists." unless @store.present?
	  elsif params[:type] == "conventional"
  	  @store = Store.find_by(mobile: params[:unique_id])
  	  return render_message 402, "Store doesn't exists." unless @store.present?
  	  return render_message 402, "Wrong password." unless @store.authenticate(params[:password])
	 end
    	device = @store.devices.create(device_params)
    	@image = @store.try(:images).map{|x| x.try(:file_url)}
    	@select = @store.as_json.merge("image" => @image).except("otp", "otp_gen_time", "unique_id", "password_digest")
    	render :json =>  {:responseCode => 200, :responseMessage => "You have successfully logged-In.", :store => @select }
  end

  def resend_otp
    @mobile = params[:mobile]
    @mobile_code = params[:code]
    @store = Store.find_by(id: params[:id])
    return render_message 402, "Store doesn't exists." unless @store.present?
    Store.generate_otp_and_send(@mobile, @mobile_code, @store)
    return render_message 200, "Otp resend successfully."
  end

  def view_profile
    @image = @current_store.try(:images).map{|x| x.try(:file_url)}
    @select = @current_store.as_json.merge("image" => @image).except("otp", "otp_gen_time", "unique_id", "password_digest")
    render json: {responseCode: 200, responseMessage: "Profile fetched successfully.",user: @select}
  end

  def update_profile
    @store = Store.where(:id.ne => @current_store.id).and({email: params[:email].try(:downcase)}, {:email.ne => ""}) if params[:email].present?
    return render_message 402, "Email must be unique." if @store.present?
    if @current_store.update_attributes(update_store_params)
      if params[:image].present?
          @current_store.images.create(file: params[:image])
          @current_store.try(:images).try(:last).try(:reload)
      end
      @image = @current_store.try(:images).map{|x| x.try(:file_url)}
      @select = @current_store.as_json.merge("image" => @image).except("otp", "otp_gen_time", "unique_id")
      render json: {responseCode: 200, responseMessage: "Store profile updated successfully.",user: @select}
    else
      render_message 402, @current_store.errors.full_messages.first
    end
  end

  def logout
    @device = Device.and({device_token: params[:device][:device_token]}, {:user_id => @current_store.id})
    render_message 200, "Logged out successfully." if @device.destroy_all  
  end

  private

  def store_params
    params.permit(:name, :store_type, :email, :website, :code, :mobile, :address, :unique_id, :touch_id, :latitude, :longitude, :description)
  end

  def update_store_params
    params.permit(:name, :email, :website, :address, :touch_id, :latitude, :longitude)
  end

end

app/helpers/stores_helper.rb
module StoresHelper
	def get_day a
		case a
		when 0
		  "Mon"
		when 1
		  "Tue"
		when 2
		  "Wed"
		when 3
		  "Thu"
		when 4
		  "Fri"
		when 5
		  "Sat"
		when 6
		  "Sun"
		else
		  "You gave me #{x} -- I have no idea what to do with that."
		end
	end
end

app/views/admin/stores/edit.html.erb
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC-lQ-u7das4d7DuTcjLii2G89FB2FqO-I&sensor=false&libraries=places"></script>
<div class="content-wrapper">
  <section class="main-block">
    <div class="container">Edit Provider
      <div class="row">
        <div class="tab-content">
  				<div class="tab-pane fade active in" id="default-tab-1">
  					<div class="tab-pane">
  							<%= form_for [:admin, @store],html: {id: "new_store"} do |f|%>
  								<div class="detail-form m-t-40 m-b-40">

                    <div class="form-group">
                      <div class="row">
                        <label class="col-sm-4 col-md-3 control-label"> Name</label>
                        <div class="col-sm-8 col-md-7">
                          <%= f.text_field :name, class: "form-control", required: true, placeholder: ""%>
                        </div>
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="row">
                        <label class="col-sm-4 col-md-3 control-label"> Email</label>
                        <div class="col-sm-8 col-md-7">
                          <%= f.text_field :email, class: "form-control", placeholder: ""%>
                        </div>
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="row">
                        <label class="col-sm-4 col-md-3 control-label"> Mobile</label>
                        <div class="col-sm-8 col-md-7">
                          <%= f.text_field :mobile, class: "form-control", placeholder: ""%>
                        </div>
                      </div>
                    </div>


                     <div class="form-group">
                      <div class="row">
                        <label class="col-sm-4 col-md-3 control-label">Store Type</label>
                        <div class="col-sm-8 col-md-7">
                          <%= f.text_field :store_type, class: "form-control", placeholder: ""%>
                        </div>
                      </div>
                    </div>

                     <div class="form-group">
                      <div class="row">
                        <label class="col-sm-4 col-md-3 control-label">Website</label>
                        <div class="col-sm-8 col-md-7">
                          <%= f.text_field :website, class: "form-control", placeholder: ""%>
                        </div>
                      </div>
                    </div>

                     <div class="form-group">
                      <div class="row">
                        <label class="col-sm-4 col-md-3 control-label">Location</label>
                        <div class="col-sm-8 col-md-7">
                          <%= f.text_field :location, class: "form-control", placeholder: ""%>
                        </div>
                      </div>
                    </div>

                     <div class="form-group">
                      <div class="row">
                        <label class="col-sm-4 col-md-3 control-label">Description</label>
                        <div class="col-sm-8 col-md-7">
                          <%= f.text_area :description, class: "form-control", placeholder: ""%>
                        </div>
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="row">
                        <label class="col-sm-4 col-md-3 control-label"> Address</label>
                        <div class="col-sm-8 col-md-7">
                          <%= f.text_area :address, class: "form-control", placeholder: ""%>
                        </div>
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="row">
                        <label class="col-sm-4 col-md-3 control-label"> Country</label>
                        <div class="col-sm-8 col-md-7">
                          <%= f.text_field :country, class: "form-control", placeholder: ""%>
                        </div>
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="row">
                        <label class="col-sm-4 col-md-3 control-label"> City</label>
                        <div class="col-sm-8 col-md-7">
                          <%= f.text_field :city, class: "form-control", placeholder: ""%>
                        </div>
                      </div>
                    </div>
               
                   

  									<div class="form-group">
  										<div class="text-center attendee-cent-s">
  											<button class="btn btn-default btn-green" type="submit">Update Provider</button>
  										</div>
									</div>
								</div>
							<%end%>
						</div>
  				</div>
        </div>
      </div>
    </div>
  </section>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $('#userdatetimepicker1').datetimepicker({
      format: 'DD/MM/YYYY',
      useCurrent: false,
      maxDate: new Date()
    });
    window.onload = function() {
      var myInput = document.getElementById('userdatetimepicker1');
      myInput.onpaste = function(e) {
        e.preventDefault();
      }
    }
  });
</script>

app/views/admin/stores/index.html.erb
 <h1 class="heading">SERVICE PROVIDER MANAGEMENT</h1>
 <div class="filter-block">
 <fieldset class="global-fieldset">
    <legend>Filter By</legend>
    <div class="filter-content user-filter">
    <%= form_tag admin_stores_path, method: :get do  %>
      <div class="row">
      <div class="col-sm-3">
          <div class="user-label">                              
           <div class="">
            <%=  text_field_tag :search, "", class:"form-control custom-control1", placeholder: "Search by Email/Name" %>
           </div>                            
         </div>
       </div> 
         <div class="col-sm-3">
          <div class="user-label">
            <div class="">
              <%=  select_tag :status,options_for_select([["All",""],["Active","1"],["Blocked","0"]]), class:"form-control custom-control1" %>
          </div>
          </div>
        </div> 
        <div class="col-sm-3">
          <div class="text-left">
            <button class="btn btn-red">Search</button>
          </div>
       </div>
    </div>
    <%end%>
  </div>
</fieldset>
  </div>
<!-- <<<<<<< HEAD
  <div class="action-btn">
  <a><%#= link_to '<i class="fa fa-pencil" aria-hidden="true"></i> Add Service Provider'.html_safe,  new_admin_store_path, :class=>"btn btn-sm btn-primary"%></a>
  <a><%#= link_to '<i class="fa fa-download" aria-hidden="true"></i> Export Sample CSV'.html_safe,  export_admin_stores_path(format: "csv") , method: :post, :class=>"btn btn-sm btn-primary"%></a>
  <a><%#= link_to '<i class="fa fa-pencil" aria-hidden="true"></i> Import CSV'.html_safe,  import_admin_stores_path(format: "csv") , method: :post, :class=>"btn btn-sm btn-primary"%></a>
======= -->
  
<div class="action-btn">
  <table>
    <tr>
      <td>
        <a>
        <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i> Add Service Provider'.html_safe,  new_admin_store_path, :class=>"btn btn-sm btn-primary"%>
        </a>
        <a>
        <%= link_to '<i class="fa fa-download" aria-hidden="true"></i> Export Sample CSV'.html_safe,  export_admin_stores_path(format: "csv") , method: :post, :class=>"btn btn-red"%>
        </a>
        <%#= link_to '<i class="fa fa-pencil" aria-hidden="true"></i> Import CSV'.html_safe,  import_admin_stores_path(format: "csv") , method: :post, :class=>"btn btn-sm btn-primary"%>

        <a>
          <%= form_tag import_admin_stores_path, multipart: true do %>
            <th><a>
              <%= file_field_tag :file, required: true , class: "btn btn-sm "%>
            </a></th>
            <th><a>
              <%= submit_tag "Import", class: "btn btn-info" %>
            </a></th>
          <%end%>
        </a>
      </td>
    </tr>
  </table>
</div>

<div class="box box-blue">
  <div class="box-body">
    <div class="custom-table table-responsive">
      <table class="table table-striped table-border">
        <thead>
          <tr>
            <th>Store Image</th>
            <th>Store Name</th>                            
            <th>Email </th>
            <th>Phone </th>
            <th>Store Type </th>
            <th>Address</th>                                                  
            <th>Action</th>
          </tr>
        </thead>
        <% @stores.each do |store| %>
        <% unless store.eql?(nil) %>
        <tbody>
          <tr>
            <td><%= store.images.present? ? image_tag(store.images.first.try(:file_url),:width => 50, :height => 50, :class => 'news-content') : image_tag("/store.png",:width => 50, :height => 50, :class => 'news-content') %></td>
            <td><%= truncate(store.try(:name), omision: "...", length: 30) %></td>
            <td><%= truncate(store.try(:email), omision: "...", length: 30) %></td>
            <td><%= truncate(store.try(:mobile), omision: "...", length: 30) %></td> 
            <td><%= (store.try(:store_type)).try(:titleize) %></td> 
            <td><%= truncate(store.try(:address), omision: "...", length: 50) %></td>                   

                             
            <td>
              <div class="action-btn">
              <%if store.admin_approved.eql?(1) %>
                      <a class = "btn btn-sm btn-success width90" href="<%= store_approve_admin_stores_path(id: store.id, admin_approved: 0) %>" onclick="return confirm('Are you sure you want to disapprove this store?')" > Approved </a>
               <% elsif store.admin_approved.eql?(0) %>
                      <a class = "btn btn-sm btn-danger width90" href="<%= store_approve_admin_stores_path(id: store.id, admin_approved: 1) %>" onclick="return confirm('Are you sure you want to approve this store?')" > Not Approved </a>  
                <% end %>
                <%= link_to '<i class="fa fa-eye" aria-hidden="true"></i> View'.html_safe, admin_store_path(id: store.id), :class=>"btn btn-sm btn-success width90"%>
                <%if store.status.eql?(1) %>
                <%= link_to '<i class="fa fa-ban" aria-hidden="true"></i> Block'.html_safe,store_status_admin_stores_path(:id => store.id), method: :post,:class=>"btn btn-sm btn-danger width90",:data => { :confirm => "Are you sure to block this store?" }%>
                <%elsif store.status.eql?(0) %>
                <%= link_to '<i class="fa fa-check-square-o" aria-hidden="true"></i> Unblock'.html_safe,store_status_admin_stores_path(:id => store.id), method: :post,:class=>"btn btn-sm btn-primary width90",:data => { :confirm => "Are you sure to activate this store?" }%>
                <%end%>      
                <%= link_to '<i class="fa fa-trash" aria-hidden="true"></i> Delete'.html_safe,  admin_store_path(store.id), method: :delete,:class=>"btn btn-sm btn-danger width90", data: {confirm: 'Are you sure to delete this store?' }%>
                <%= link_to '<i class="fa fa-edit" aria-hidden="true"></i> Edit'.html_safe,  edit_admin_store_path(store.id), :class=>"btn btn-sm btn-primary width90"%>
              </div>  
            </td>
          </tr>                                
        </tbody>
        <%end%>
        <%end%>
      </table>
      <%= "No store found." unless @stores.present?%>
    </div>                     
  </div>
</div>

<div class="custom-pagination">
  <%= will_paginate @stores %>
</div>

</div>
</div>
</div>