config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  api_version(:module => "api/v1/customer", :header => {:name => "Accept", :value => "application/centarium.com; version=1"}) do
    resources :users do
      collection do
        post :sign_up
        get :generate_code
        post :login
        post :verify_otp
        post :resend_otp
        post :logout
        get :view_profile
        post :update_profile
        post :send_otp_mobile
        post :otp_change_mobile
        post :upload_doc
        post :forgot_password
        post :update_password
      end
    end    
    resources :stores do
      collection do
        post :store_detail
        post :add_fav
      end
    end
    resources :products do
      collection do
        post :product_list
        post :product_detail
        post :product_review
        post :write_review
        post :add_fav
      end
    end
    resources :socials do
      collection do
        post :social_login
      end
    end
    resources :static_contents  do
      collection do
        post :static_content 
        post :contact_us   
      end
    end
    resources :notifications do
      collection do
        post :notification_list
        post :delete_notification
      end
    end
    namespace :storeapi do
      resources :stores do
        collection do
          post :sign_up
          get :generate_code
          post :login
          post :verify_otp
          post :resend_otp
          post :logout
          get :view_profile
          post :update_profile
          post :send_otp_email
          post :otp_change_email
          post :upload_doc
          post :send_otp_mobile
          post :otp_change_mobile
          post :forgot_password
          post :update_password
        end
      end
      resources :products do
        collection do
          post :product_update
          post :product_detail
          post :product_list
          post :product_review
        end
      end
      resources :campaigns do
        collection do
          get :product_list_name
          post :edit_campaign
          post :list_campaign
          post :detail_campaign
        end
      end
    end
  end
  namespace :admin do
    root :to => "home#index"
    resources :sessions
    resources :home do
      collection do
        get :forget_password
        patch :reset_password
      end
    end
    resources :admin_users do
      collection do
        post :user_status
      end
      member do
        get :change_password
        post :update_password
      end
    end
    resources :users do
      collection do
        get :user_status
        get :user_approve
      end
    end
    resources :stores do
      collection do
        post :store_status
        get :store_approve
        post :import
        post :export
      end
    end
    resources :products do
     collection do
        post :product_status
     end
    end
    resources :distance do
      collection do
        post :save_distance
      end
    end
    resources :static_pages
    resources :faqs    
    resources :contact_us
    resources :tokens
    get '/login' => 'sessions#new'
  end
  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_action :require_admin_user, except: [:forget_password, :reset_password]
  # before_action :find_admin_user, except: [:forget_password, :change_password]

  def index
    
  end

  def edit
  end

  def update
    
  end

  def show
  end

  def forget_password
  end

  def reset_password
    @admin_user = AdminUser.find_by(email: params[:admin_user][:email])
    if @admin_user.present?
      @password = SecureRandom.hex(5)
      @admin_user.update_attributes(password: @password)
      UserMailer.forget_password(@admin_user, @password).deliver_now
      redirect_to admin_home_index_path
      flash[:notice] = "If you have entered correct email, you will receive your password to email."
    else
      redirect_to forget_password_admin_home_index_path 
      flash[:error] = "Invalid Email, Please try again."
    end
  end
end

app/views/admin/home/edit.html.erb
<div class="content-wrapper">
  <section class="main-block">
    <div class="container">
      <div class="row">
        <div class="tab-content">
  				<div class="tab-pane fade active in" id="default-tab-1">
  					<div class="tab-pane">
  							<%= form_for @admin_user,url: admin_home_path,method: :patch,html: {id: "new_admin_user"} do |f|%>
  								<div class="detail-form m-t-40 m-b-40">

  									<div class="form-group">
  										<div class="row">
  											<label class="col-sm-4 col-md-3 control-label">User Name</label>
  											<div class="col-sm-8 col-md-7">
  											  <%= f.text_field :name, class: "form-control", required: true, placeholder: ""%>
  											</div>
  										</div>
  									</div>
                    
                    <div class="form-group">
                      <div class="row">
                        <label class="col-sm-4 col-md-3 control-label">Email</label>
                        <div class="col-sm-8 col-md-7">
                          <%= f.email_field :email, class: "form-control", required: true, placeholder: ""%>
                        </div>
                      </div>
                    </div>
                    
                    <div class="form-group">
                      <div class="row">
                        <label class="col-sm-4 col-md-3 control-label">Password</label>
                        <div class="col-sm-8 col-md-7">
                          <%= f.password_field :password, class: "form-control", required: true, placeholder: ""%>
                          <h12>Change your password with updating your profile.</h12>
                        </div>
                      </div>
                    </div>  

                    <div class="form-group">
                        <div class="row">
                          <label class="col-sm-4 col-md-3 control-label">Confirm Password</label>
                          <div class="col-sm-8 col-md-7">
                            <%= f.password_field :confirm_password, class: "form-control", required: true, placeholder: ""%>
                          </div>
                        </div>
                      </div>
                    
                    <div class="form-group">
  										<div class="row">
  											<label class="col-sm-4 col-md-3 control-label">Image</label>
  											<div class="col-sm-8 col-md-7">
                          <% if @admin_user.try(:image).present? %>
                            <div class="uploadimg">
                              <%= image_tag @admin_user.image.try(:url),:class=>"fileinput-preview thumbnail", :id=> "black_cat_img", :alt=>"", :width=>"200px", :height=>"150px" %>
                            </div>
                            <div class="addupload addupload1">
                              <div class="fileUpload btn btn-pri choose-file">
                                <%= f.file_field :image,:class=>"btn btn-pri btn-blue btn-file upload",data: { preview_element_id: 'black_cat_img', preview_element_type: 'id'}, :accept=>"Image/*" %>
                              </div>
                            </div>
                          <%else%>
                            <div class="uploadimg">
                              <img src="/1.png" class="fileinput-preview thumbnail" id= "black_cat_img" alt="" width="200px" height="150px">
                            </div>
                            <div class="addupload addupload1">
                              <div class="fileUpload btn btn-pri choose-file">
                                <%= f.file_field :image,:class=>"btn btn-pri btn-blue btn-file upload",data: { preview_element_id: 'black_cat_img', preview_element_type: 'id'}, required: true, :accept=>"Image/*" %>
                              </div>
                            </div>
                          <%end%>
  											</div>
  										</div>
  									</div>

  									<div class="form-group">
  										<div class="text-center attendee-cent-s">
  											<button class="btn btn-default btn-green" type="submit">Submit</button>

  										</div>
									</div>
								</div>
							<%end%>
						</div>
  				</div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/admin/home/forget_password.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,width=device-width,user-scalable=no">
  <meta http-equiv="Cache-control" content="no-store">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <title>Centareum</title>

  <style type="text/css">
    #append_wrapper>.row:first-child {display:none;}
  </style>  
</head>
<body>
 <!--  <header class="beforelogin">
    <div class="logo"><a href="/admin/login"><img src="/assets/logo1.png"></a></div>
  </header> -->
    <div class="before-login-wrapper">
      <div class="login-main-content">
        <div class="before-login-logo">
             
         </div>
         <div class="inner-content clearfix">
            <div class="login-content-box">
              <h2 class="heading">Forgot password</h2>
              <p class="login-text">Please enter your registered email address so that we can send you a temporary login password to your email.</p>
             <%= form_for(:admin_user, url: reset_password_admin_home_index_path,method: :patch,:class=> "form-control",html: {id: "forgot-idenity"}) do |f| %>
                <div class="form-group">
                  <%= f.email_field :email, class: 'form-control', placeholder: "Email", required: true,autocomplete: "off" %>
                </div>
                <div class="button-box mt30">
                  <button type="submit" class="btn btn-red width100">Reset Password</button>
                </div>                     
                <br>
                <div class="form-group">
                  <div class="col-sm-12">
                    Remember Password? <a href="/admin" class="text-center color-red">Click Here</a> for Login
                  </div>
                </div>
              <%end%>        
                 
            </div>  
          </div>
        </div>  
      </div>
        <div class="copyrights">Centareum © 2018 All Rights Reserved.</div>
</body>
</html>
<script>
$(document).ready(function(){

  $("#forgot-idenity").validate({
    // Specify the validation rules
    // debug: true,
    rules: {
      "admin_user[email]": {
        required: true,
        emailRegex: true,
        minlength: 2,
        maxlength: 100
      },
    },
    // Specify the validation error messages
    // messages: {
    //   "state[name]": {
    //     required: "Enter a name",
    //     minlength: "Title must be more than 2 characters.",
    //     maxlength: "Title must be lass than 100 characters.",
    //   },
    // },
  });
  $.validator.addMethod("emailRegex", function(value, element) {
      return this.optional(element) || /^(?=[^@]*[A-Za-z])([a-zA-Z0-9])(([a-zA-Z0-9])*([\._-])?([a-zA-Z0-9]))*@(([a-zA-Z0-9\-])+(\.))+([a-zA-Z]{2,4})+$/i.test(value);
  }, "Please enter a valid email address.");
});

</script>

app/views/admin/home/index.html.erb
<h1 class="heading">NEXAMIND ANALYTICS</h1>
<div class="info-box-block">
  <div class="row">
      <div class="col-md-3 col-sm-6">
          <div class="info-box ">
            <fieldset class="global-fieldset bg-green">
              <legend>Total Active Customers</legend>
              <div class=" info-txt">
                    <p><%= User.where(status: 1).count %></p>
                     <!-- <a href="/admin/users" class="btn btn-red"> View Details </a> -->
              </div>
            </fieldset>
          </div>
      </div>
      <div class="col-md-3 col-sm-6">
          <div class="info-box ">
            <fieldset class="global-fieldset bg-green">
              <legend>Total Customers</legend>
              <div class=" info-txt">
                    <p><%= User.count %></p>
                     <!-- <a href="/admin/stores" class="btn btn-red"> View Details </a> -->
              </div>
            </fieldset>
          </div>
      </div>
      <div class="col-md-3 col-sm-6">
          <div class="info-box ">
            <fieldset class="global-fieldset bg-green">
              <legend>Total Revenue</legend>
              <div class=" info-txt">
                    <p><%= Store.count %></p>
                     <!-- <a href="/admin/products" class="btn btn-red"> View Details </a> -->
              </div>
            </fieldset>
          </div>
      </div>
      <div class="col-md-3 col-sm-6">
          <div class="info-box ">
            <fieldset class="global-fieldset bg-green">
              <legend>Total Transactions</legend>
              <div class=" info-txt">
                <p><%= Store.count %></p>
                <!-- <a href="#" class="btn btn-red"> View Details </a> -->
              </div>
            </fieldset>
          </div>
      </div>
   </div>
   
   
   <div class="row mt20">
      <div class="col-sm-6">
          <div class="info-box ">
            <fieldset class="global-fieldset bg-yellow">
              <legend>Total</legend>
              <div class=" info-txt">
                <%#= line_chart {"Football" => 10, "Basketball" => 5},colors: ["#169BD5"] %>
                <%= timeline [
  ["Washington", "1789-04-29", "1797-03-03"],
  ["Adams", "1797-03-03", "1801-03-03"],
  ["Jefferson", "1801-03-03", "1809-03-03"]
] %>
              </div>
            </fieldset>
          </div>
      </div>
      <div class="col-sm-6">
          <div class="info-box ">
            <fieldset class="global-fieldset bg-green">
              <legend>Total</legend>
              <div class=" info-txt">
                <%#= pie_chart User.group(:gender).count,colors: ["#169BD5","#f82323"] %>
              </div>
            </fieldset>
          </div>
      </div>
   </div>
    <div class="row mt20">
      <div class="col-sm-6">
          <div class="info-box ">
            <fieldset class="global-fieldset bg-yellow">
              <legend>Totals</legend>
              <div class=" info-txt">
                <%#= line_chart Message.group_by_day(:created_at).count,colors: ["#169BD5"] %>
              </div>
            </fieldset>
          </div>
      </div>
      <div class="col-sm-6">
          <div class="info-box ">
            <fieldset class="global-fieldset bg-green">
              <legend>Total</legend>
              <div class=" info-txt">
                <%#= line_chart Post.group_by_day(:updated_at).count,colors: ["#169BD5"] %>
              </div>
            </fieldset>
          </div>
      </div>
   </div>
</div>
              

app/views/admin/home/new.html.erb
<p>gdh</p>>

app/views/admin/home/show.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1> Admin User Details</h1>

  </section>

  <!-- Main content -->
  <section class="content">

   <div class="box box-info">
     <div class="text-right attendee-cent-s form-group">
      <%= link_to "Edit", edit_admin_home_path, :class => "btn btn-default btn-green" %>
     </div>
          <!-- /.box-header -->
      <div class="box-body box-profile">
          <div class="profile-box">
          <div class="form-group has-feedback text-center">
            <%= @admin_user.image.present? ? image_tag(@admin_user.image.try(:url),:width => 100, :height => 100, :class => 'profile-ab') : image_tag("/1.png",:width => 100, :height => 100, :class => 'profile-ab') %>
          </div>
          <h3 class="profile-username text-center"><%= @admin_user.name%></h3>
          <p class="text-muted text-center"><%#= @admin_user.address%></p>

        <div class="profile-inner">
          <div class="p-blocks">
              <label class="view-a left-a">Name</label>
              <span class="view-a right-a"><%= @admin_user.name%></span>
          </div>
          <div class="p-blocks">
              <label class="view-a left-a">Email</label>
              <span class="view-a right-a"><%= @admin_user.email%></span>
          </div>
          <!-- <div class="p-blocks">
              <label class="view-a left-a">Address</label>
              <span class="view-a right-a"><%#= @admin_user.address%></span>
          </div> -->
      </div>

          </div>
      </div>
    </div>

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->