config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  api_version(:module => "api/v1/customer", :header => {:name => "Accept", :value => "application/centarium.com; version=1"}) do
    resources :users do
      collection do
        post :sign_up
        get :generate_code
        post :login
        post :verify_otp
        post :resend_otp
        post :logout
        get :view_profile
        post :update_profile
        post :send_otp_mobile
        post :otp_change_mobile
        post :upload_doc
        post :forgot_password
        post :update_password
      end
    end    
    resources :stores do
      collection do
        post :store_detail
        post :add_fav
      end
    end
    resources :products do
      collection do
        post :product_list
        post :product_detail
        post :product_review
        post :write_review
        post :add_fav
      end
    end
    resources :socials do
      collection do
        post :social_login
      end
    end
    resources :static_contents  do
      collection do
        post :static_content 
        post :contact_us   
      end
    end
    resources :notifications do
      collection do
        post :notification_list
        post :delete_notification
      end
    end
    namespace :storeapi do
      resources :stores do
        collection do
          post :sign_up
          get :generate_code
          post :login
          post :verify_otp
          post :resend_otp
          post :logout
          get :view_profile
          post :update_profile
          post :send_otp_email
          post :otp_change_email
          post :upload_doc
          post :send_otp_mobile
          post :otp_change_mobile
          post :forgot_password
          post :update_password
        end
      end
      resources :products do
        collection do
          post :product_update
          post :product_detail
          post :product_list
          post :product_review
        end
      end
      resources :campaigns do
        collection do
          get :product_list_name
          post :edit_campaign
          post :list_campaign
          post :detail_campaign
        end
      end
    end
  end
  namespace :admin do
    root :to => "home#index"
    resources :sessions
    resources :home do
      collection do
        get :forget_password
        patch :reset_password
      end
    end
    resources :admin_users do
      collection do
        post :user_status
      end
      member do
        get :change_password
        post :update_password
      end
    end
    resources :users do
      collection do
        get :user_status
        get :user_approve
      end
    end
    resources :stores do
      collection do
        post :store_status
        get :store_approve
        post :import
        post :export
      end
    end
    resources :products do
     collection do
        post :product_status
     end
    end
    resources :distance do
      collection do
        post :save_distance
      end
    end
    resources :static_pages
    resources :faqs    
    resources :contact_us
    resources :tokens
    get '/login' => 'sessions#new'
  end
  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps
  
  field :name, type: String
  field :cost, type: String
  field :price, type: String
  field :quantity, type: String
  field :sku, type: String
  field :availed_size, type: Array
  field :availed_color, type: Array
  field :description, type: String
  field :category, type: String
  field :subcategory, type: String
  field :event_date, type: Date
  field :start_time, type: DateTime
  field :end_time, type: DateTime
  field :status, type: Integer, default: 1


  belongs_to :store
  has_many :images, as: :imageable, class_name: "Image"
  has_many :product_ratings, dependent: :destroy
  has_many :fav_products, dependent: :destroy
  has_many :product_campaigns, dependent: :destroy

  def campaigns
    Campaign.in(id: product_campaigns.pluck(:campaign_id))
  end
end

app/controllers/admin/products_controller.rb
require 'will_paginate/array'
class Admin::ProductsController < ApplicationController
  before_action :require_admin_user
  before_action :find_product, except: [:index, :vendor_list]

  def index
    if params[:search].present? && params[:status].present?
      @search = Product.and({name: Regexp.new(".*#{params[:search]}.*","i")}, {status: params[:status]})
      @products = @search.order("created_at desc").paginate(:page => params[:page], :per_page => 10)
    elsif params[:status].present? && params[:status] != ""
      @search = Product.where({status: params[:status]})
      @products = @search.order("created_at desc").paginate(:page => params[:page], :per_page => 10)
    elsif params[:search].present? && params[:search] != ""
      @search = Product.where({name: Regexp.new(".*#{params[:search]}.*","i")})
      @products = @search.order("created_at desc").paginate(:page => params[:page], :per_page => 10)
    else
      @products = Product.all.order("created_at desc").paginate(:page => params[:page], :per_page => 10)
    end
  end

  def product_status
   if @product.status.eql?(2) 
      @product.update_attributes(status: 1)
      redirect_to  admin_products_path,notice: "Product activated successfully."
   elsif @product.status.eql?(1) 
      @product.update_attributes(status: 2)
      redirect_to  admin_products_path, notice: "Product blocked successfully."
   end
  end

  def edit
  end

  def update
    if @product.update_attributes(product_params)
			redirect_to admin_products_path, notice: 'Product updated Successfully.'
		else
      flash[:error] = @product.errors.full_messages.first
			render :edit
		end
  end

  def show
    
  end

  def destroy
    if @product.destroy
      redirect_to  admin_products_path
    else
      flash[:error] = @product.errors.full_messages.first
      redirect_to  admin_products_path
    end
  end


  private
  def find_product
    @product = Product.find_by(id: params[:id])
    redirect_to admin_products_path unless @product
  end

  def product_params
		params.require(:product).permit(:email,:password,:name,:mobile,:address,:status,:gender, :country, :city, :code)
	end
end

app/controllers/api/v1/customer/products_controller.rb
class Api::V1::Customer::ProductsController < ApplicationController
  before_action :find_user

  def product_list
  	@store = Store.and({:id => params[:id]}, {:store_type => params[:store_type]}).first
  	return render_message 402, "Store doesn't exists." unless @store.present?
  	@products = @store.products
  	if params[:do] == "search"
  	  product_name = Regexp.new(".*#{params[:search]}.*","i")
  	  @products = @products.any_of({:name => product_name}) if params[:search].present?
	  elsif params[:do] == "filter"
  	  @products = @products.and({:price.gte => params[:min]}, {:price.lte => params[:max]}) if params[:min].present? && params[:max].present?
  	  # if @store.store_type == 1
  	  	# @products = @products.where(:category => params[:category])	
  	  if @store.store_type == 0
  	  	@products = @products.any_of({:category => params[:category]}, {:subcategory => params[:subcategory]}, {:subcategory => params[:subcategory]}, {:availed_size => params[:availed_size]}, {:availed_color => params[:availed_color]}) 
  	  end
	  end
  	@products = @products.map{|x| x.attributes.merge(rating: (x.product_ratings.pluck(:rate).map(&:to_i).sum > 0) ? ((x.product_ratings.pluck(:rate).map(&:to_i).sum.to_f)/(x.product_ratings.count)) : 0, is_fav: (x.fav_products.find_by(user_id: @current_user.id).eql?(nil) ? false : true), image: (x.images.try(:first).try(:file_url) if x.images.try(:first).present?))}
    render :json =>  {responseCode: 200, responseMessage: "Products fetched successfully.", products: @products}
  end

  def product_detail
    @product = Product.find_by(id: params[:product_id])
    return render_message 402, "Product doesn't exists." unless @product.present?
    product_hash = {}
    product_hash[:product] = @product
    product_hash[:image] = @product.try(:images)
    render :json => { :responseCode => 200,
                    :responseMessage => "Product fetched successfully.",
                    :products => product_hash
                   }
  end

  def product_review
  	if params[:product_id]
  	  @product = Product.find_by(id: params[:product_id])
  	  return render_message 402, "Product doesn't exists." unless @product.present?
  	  rating = @product.product_ratings
	  else
  	  @store = Store.and({:id => params[:id]}, {:store_type => params[:store_type]}).first	
  	  rating = @store.products.map{|x| x.product_ratings}.try(:flatten)
	  end
    product_arr = []
    rating.each do |product|
      product_arr << product.as_json.merge("user" => product.user.as_json.slice("_id", "email", "name").merge("image" => product.user.try(:image).try(:file_url)))
    end
    render :json => { :responseCode => 200,
                    :responseMessage => "Reviews fetched successfully.",
                    :reviews => product_arr
                   }
  end

  def write_review
  	@product = Product.find_by(id: params[:product_id])
  	return render_message 402, "Product doesn't exists." unless @product.present?
  	@review = @product.product_ratings.new(rate: params[:rate], review: params[:review], user_id: @current_user)
  	if @review.save
  	  render :json => { :responseCode => 200,
	                    :responseMessage => "Review created successfully.",
	                    :reviews => @review
	                   }
  	else
  	  render_message 402, "Review not created."	
  	end
  end
    
  def add_fav
    @product = Product.find_by(id: params[:product_id])
	  return render_message 402, "Product doesn't exists." unless @product.present?
    @fav_store = @product.fav_products.find_or_create_by(product_id: params[:product_id], user_id: @current_user.id)
    if @fav_store.update(is_liked: params[:is_liked])
  	  render :json => { :responseCode => 200,
  	                  :responseMessage => "Product favorite status updated successfully.",
  	                  :fav_store => @fav_store
  	                 }
  	else
  	  render_message 402, "Product favorite status not updated."
    end 	
  end
end

app/controllers/api/v1/storeapi/products_controller.rb
class Api::V1::Storeapi::ProductsController < ApplicationController
  require 'will_paginate/array'
  before_action :find_store
  include ProductsConcern

  def create
  	@product = @current_store.products.new(product_params)
  	if @product.save
  	  product_hash = {}
  	  product_hash[:product] = @product
  	  product_img = @product.images.reload if params[:images_attributes].present?
      product_hash[:images_attributes] = product_img
  	  render :json => { :responseCode => 200,
  	                  :responseMessage => "Product created successfully.",
  	                  :products => product_hash
  	                 }
  	else
      return render_message 402, "Product not created."
    end           
  end	

  def product_list
    @products = all_product_list(params, @current_store)
    @merge = []
    @products.each do |similar|
      @merge << similar.as_json.merge("images_attributes" => similar.try(:images))
    end
    all_product = @merge.paginate(:page => params[:page], :per_page => 10)
    render :json => { :responseCode => 200,
                      :responseMessage => "Product list fetched successfully.",
                      :products => all_product,
                       pagination: { page_no: all_product.current_page, per_page: 10, max_page_size: all_product.total_pages, total_records: all_product.total_entries }
                    }
  end

  def product_update
    @product = @current_store.products.find_by(id: params[:product_id])
    return render_message 402, "Product doesn't exists." unless @product.present?
    if @product.update_attributes(product_params)
      product_hash = {}
      product_hash[:product] = @product
      product_img = @product.images.reload if params[:images_attributes].present?
      product_hash[:images_attributes] = product_img
      render :json => { :responseCode => 200,
                      :responseMessage => "Product updated successfully.",
                      :products => product_hash
                     }
    else
      return render_message 402, "Product not updated."
    end            
  end

  def product_detail
    @product = @current_store.products.find_by(id: params[:product_id])
    return render_message 402, "Product doesn't exists." unless @product.present?
    product_hash = {}
    product_hash[:product] = @product
    product_hash[:images_attributes] = @product.try(:images)
    render :json => { :responseCode => 200,
                    :responseMessage => "Product fetched successfully.",
                    :products => product_hash
                   }
  end

  def product_review
    @product = @current_store.products.find_by(id: params[:product_id])
    return render_message 402, "Product doesn't exists." unless @product.present?
    product_arr = []
    @product.product_ratings.each do |product|
      product_arr << product.as_json.merge("user" => product.user.as_json.slice("_id", "email", "name").merge("image" => product.user.try(:image).try(:file_url)))
    end
    render :json => { :responseCode => 200,
                    :responseMessage => "Reviews fetched successfully.",
                    :reviews => product_arr
                   }
  end

  private

  def product_params
    params.permit(:name, :cost, :price, :quantity, :sku, :description, :category, :subcategory, :latitude, :longitude, :description, :event_date, :start_time, :end_time, availed_size: [], availed_color: [],
    images_attributes: [:id, :file, :_destroy])
  end
end

app/helpers/api/v1/storeapi/products_helper.rb
module Api::V1::Storeapi::ProductsHelper
end

app/views/admin/products/index.html.erb
 <h1 class="heading">PRODUCT MANAGEMENT</h1>
 <div class="filter-block">
 <fieldset class="global-fieldset">
    <legend>Filter By</legend>
    <div class="filter-content user-filter">
    <%= form_tag admin_products_path, method: :get do  %>
    <div class="row">
      <div class="col-sm-3">
          <div class="user-label">                              
           <div class="">
            <%=  text_field_tag :search, "", class:"form-control custom-control1", placeholder: "Search by Name" %>
           </div>                            
         </div>
       </div> 
         <div class="col-sm-3">
          <div class="user-label">
            <div class="">
              <%=  select_tag :status,options_for_select([["All",""],["Active",1],["Blocked",2]]),class:"form-control custom-control1" %>
          </div>
          </div>
        </div> 
       <div class="col-sm-3">
        <div class="text-left">
          <button class="btn btn-red">Search</button>
        </div>
      </div>
    </div>
    <%end%>
  </div>
</fieldset>
  </div>
<div class="box box-blue">
  <div class="box-body">
    <div class="custom-table table-responsive">
      <table class="table table-striped table-border">
        <thead>
          <tr>
            <th>Product Image</th>
            <th>Product Name</th>                            
            <th>Cost </th>
            <th>Price </th>
            <th>Quantity </th>
            <th>Action</th>
          </tr>
        </thead>
        <% @products.each do |product| %>
        <% unless product.eql?(nil) %>
        <tbody>
          <tr>
            <td><%= product.images.present? ? image_tag(product.images.try(:first).try(:file_url),:width => 200, :height => 100, :class => 'news-content') : image_tag("/1.png",:width => 200, :height => 100, :class => 'news-content') %></td>

            <td><%= truncate(product.try(:name), omision: "...", length: 30) %></td>
            <td><%= truncate(product.try(:cost), omision: "...", length: 30) %></td>
            <td><%= truncate(product.try(:price), omision: "...", length: 30) %></td> 
            <td><%= product.try(:quantity) %></td>                         
            <td>
              <div class="action-btn">
                <%if product.try(:status).eql?(1)%>
                <%= link_to '<i class="fa fa-ban" aria-hidden="true"></i> Block'.html_safe,product_status_admin_products_path(:id => product.id), method: :post,:class=>"btn btn-sm btn-danger",:data => { :confirm => "Are you sure to block this product?" }%>
                <%elsif product.try(:status).eql?(2)%>
                <%= link_to '<i class="fa fa-check" aria-hidden="true"></i> Unblock'.html_safe,product_status_admin_products_path(:id => product.id), method: :post,:class=>"btn btn-sm btn-primary",:data => { :confirm => "Are you sure to activate this product?" }%>
                <%end%>    
                <a><%= link_to '<i class="fa fa-eye" aria-hidden="true"></i> View'.html_safe, admin_product_path(id: product.id), :class=>"btn btn-sm btn-success"%></a>
                <!-- <a><%#= link_to '<i class="fa fa-trash" aria-hidden="true"></i> Delete'.html_safe,  admin_product_path(product.id), method: :delete,:class=>"btn btn-sm btn-danger", data: {confirm: 'Are you sure to delete this product?' }%></a> -->
              </div>  
            </td>
          </tr>                                
        </tbody>
        <%end%>
        <%end%>
      </table>
      <center>
      <%= "No products found." unless @products.present?%>
      </center>
    </div>                     
  </div>
</div>

<div class="custom-pagination">
  <%= will_paginate @products %>
</div>

</div>
</div>
</div>