config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  api_version(:module => "api/v1/customer", :header => {:name => "Accept", :value => "application/centarium.com; version=1"}) do
    resources :users do
      collection do
        post :sign_up
        get :generate_code
        post :login
        post :verify_otp
        post :resend_otp
        post :logout
        get :view_profile
        post :update_profile
        post :send_otp_mobile
        post :otp_change_mobile
        post :upload_doc
        post :forgot_password
        post :update_password
      end
    end    
    resources :stores do
      collection do
        post :store_detail
        post :add_fav
      end
    end
    resources :products do
      collection do
        post :product_list
        post :product_detail
        post :product_review
        post :write_review
        post :add_fav
      end
    end
    resources :socials do
      collection do
        post :social_login
      end
    end
    resources :static_contents  do
      collection do
        post :static_content 
        post :contact_us   
      end
    end
    resources :notifications do
      collection do
        post :notification_list
        post :delete_notification
      end
    end
    namespace :storeapi do
      resources :stores do
        collection do
          post :sign_up
          get :generate_code
          post :login
          post :verify_otp
          post :resend_otp
          post :logout
          get :view_profile
          post :update_profile
          post :send_otp_email
          post :otp_change_email
          post :upload_doc
          post :send_otp_mobile
          post :otp_change_mobile
          post :forgot_password
          post :update_password
        end
      end
      resources :products do
        collection do
          post :product_update
          post :product_detail
          post :product_list
          post :product_review
        end
      end
      resources :campaigns do
        collection do
          get :product_list_name
          post :edit_campaign
          post :list_campaign
          post :detail_campaign
        end
      end
    end
  end
  namespace :admin do
    root :to => "home#index"
    resources :sessions
    resources :home do
      collection do
        get :forget_password
        patch :reset_password
      end
    end
    resources :admin_users do
      collection do
        post :user_status
      end
      member do
        get :change_password
        post :update_password
      end
    end
    resources :users do
      collection do
        get :user_status
        get :user_approve
      end
    end
    resources :stores do
      collection do
        post :store_status
        get :store_approve
        post :import
        post :export
      end
    end
    resources :products do
     collection do
        post :product_status
     end
    end
    resources :distance do
      collection do
        post :save_distance
      end
    end
    resources :static_pages
    resources :faqs    
    resources :contact_us
    resources :tokens
    get '/login' => 'sessions#new'
  end
  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/admin/users_controller.rb
require 'will_paginate/array'
class Admin::UsersController < ApplicationController
  before_action :require_admin_user
  before_action :find_user, except: [:index, :vendor_list]

    def index
      # if params[:search].present?
      #   if params[:gender].present? && params[:status].present?
      #     @search = User.any_of({name: Regexp.new(".*#{params[:search]}.*","i")},{email: Regexp.new(".*#{params[:search]}.*","i")},{mobile: Regexp.new(".*#{params[:search]}.*","i")}).where(gender: params[:gender],status: params[:status])       
      #   elsif params[:gender].present?
      #     @search = User.any_of({name: Regexp.new(".*#{params[:search]}.*","i")},{email: Regexp.new(".*#{params[:search]}.*","i")},{mobile: Regexp.new(".*#{params[:search]}.*","i")}).where(gender: params[:gender],status: (0..1))       
      #   elsif params[:status].present?
      #     @search = User.any_of({name: Regexp.new(".*#{params[:search]}.*","i")},{email: Regexp.new(".*#{params[:search]}.*","i")},{mobile: Regexp.new(".*#{params[:search]}.*","i")}).where(status: params[:status])       
      #   end 
      # elsif params[:gender].present?
      #     if params[:status].present?
      #       @search = User.where(status: params[:status], gender: params[:gender])
      #     end
      # elsif params[:status].present?
      #       @search = User.where(status: params[:status])
      # else      
      #   @search = User.where(status: (0..1))     
      # end     
        @users = User.where(status: (0..1)).order("created_at desc").paginate(:page => params[:page], :per_page => 10)   
    end

  def user_status
   if params[:status] == "1" 
      @user.update_attributes(status: 1)
      redirect_to  request.referer,notice: "User's account activated successfully."
   elsif params[:status] == "0" 
      @user.update_attributes(status: 0)
      redirect_to  request.referer, notice: "User's account blocked successfully."
   end
  end

  def user_approve
    @user.update_attributes(admin_approved: 1) if params[:admin_approved] == "1"
    @user.update_attributes(admin_approved: 0) if params[:admin_approved] == "0"
    redirect_to request.referer
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
			redirect_to admin_users_path, notice: 'User updated Successfully.'
		else
      flash[:error] = @user.errors.full_messages.first
			render :edit
		end
  end

  def show
    
  end

  def destroy
    if @user.destroy
      redirect_to  admin_users_path
    else
      flash[:error] = @user.errors.full_messages.first
      redirect_to  admin_users_path
    end
  end


  private
  def find_user
    @user = User.find_by(id: params[:id])
    redirect_to admin_users_path unless @user
  end

  def user_params
		params.permit(:email,:password,:name,:mobile,:address,:status,:gender, :country, :city, :code)
	end
end

app/controllers/api/v1/customer/users_controller.rb
class Api::V1::Customer::UsersController < ApplicationController
  before_action :find_user, :only=>[:logout, :view_profile, :update_profile, :send_otp_mobile, :otp_change_mobile, :send_otp_mobile, :upload_doc]

  def generate_code
    unique_code = User.generate_code
    render :json => {responseCode: 200, responseMessage: "Code generated successfully.", code: unique_code}
  end

  def sign_up
    @user = User.any_of({:unique_id => params[:unique_id]},{:email => params[:email].try(:downcase)}, {:mobile => params[:mobile]})
    return render_message 402, "User already exist." if @user.present?
    @user = User.new(user_params)
    @user.build_image(file: params[:image]) if params[:image].present?
    if @user.save
  	  token = User.generate_token
      @user.update_attributes(access_token: token, status: 2, sign_in_count: @user.sign_in_count.to_i + 1, current_sign_in_at: DateTime.current)
      @user.try(:image).try(:reload)
      @select = @user.as_json.merge("image" => @user.try(:image).try(:file_url)).except("otp", "otp_gen_time", "unique_id")
      User.generate_otp_and_send(@user.mobile, @user.code, @user)
  	  render :json =>  {:responseCode => 200, :responseMessage => "Signup successfully.", user: @select}
    else
      render_message 402, @user.errors.full_messages.first
    end
  end	

  def verify_otp
    @user = User.find_by(mobile: params[:mobile])
    return render_message 402, "User doesn't exist." unless @user.present?
    if @user.otp == params[:otp]
      if @user.otp_expired?
        return render_message 402, "OTP is expired."
      else
        @user.update_attributes(otp: nil, status: 1, sign_in_count: @user.sign_in_count.to_i + 1, current_sign_in_at: DateTime.current)
        @select = @user.as_json.merge("image" => @user.try(:image).try(:file_url)).except("otp", "otp_gen_time", "unique_id")
        device = @user.devices.create(device_params) 
        render :json =>  {:responseCode => 200, :responseMessage => "Otp verified successfully.", :user => @select }
      end
    else
      return render_message 402, "OTP is not valid."
    end
  end

  def login
    if params[:type] == "seed"
      @user = User.find_by(unique_id: params[:unique_id])
      return render_message 402, "User doesn't exists." unless @user.present?
    elsif params[:type] == "conventional"
      @user = User.any_of({:email => params[:email].try(:downcase)}, {:mobile => params[:mobile]}).first
      return render_message 402, "User doesn't exists." unless @user.present?
      return render_message 402, "Wrong password." unless @user.valid_password?(params[:password])
    end
      @user.update_attributes(sign_in_count: @user.sign_in_count.to_i + 1, current_sign_in_at: DateTime.current)
  	  device = @user.devices.create(device_params)
      @select = @user.as_json.merge("image" => @user.try(:image).try(:file_url)).except("otp", "otp_gen_time", "unique_id")
      render :json =>  {:responseCode => 200, :responseMessage => "You have successfully logged-In.", :user => @select }

  end

  def resend_otp
    @mobile = params[:mobile]
    @mobile_code = params[:code]
    @user = User.find_by(id: params[:id])
    return render_message 402, "User doesn't exists." unless @user.present?
    User.generate_otp_and_send(@mobile, @mobile_code, @user)
    return render_message 200, "Otp resend successfully."
  end

  def view_profile
    @select = @current_user.as_json.merge("image" => @current_user.try(:image).try(:file_url)).except("otp", "otp_gen_time", "unique_id")
    render json: {responseCode: 200, responseMessage: "Profile fetched successfully.",user: @select}
  end

  def update_profile
    @users = User.where(:id.ne => @current_user.id).and({email: params[:email].try(:downcase)}, {:email.ne => ""}) if params[:email].present?
    return render_message 402, "Email must be unique." if @users.present?
    if params[:old_password].present?
      return render_message 402, "Old password is wrong." unless @current_store.valid_password?(params[:old_password])
    end 
    if @current_user.update_attributes(update_user_params)
      if params[:image].present?
          @current_user.create_image(file: params[:image])
          @current_user.try(:image).try(:reload)
      end
      @select = @current_user.as_json.merge("image" => @current_user.try(:image).try(:file_url)).except("otp", "otp_gen_time", "unique_id")
      render json: {responseCode: 200, responseMessage: "Profile updated successfully.",user: @select}
    else
      render_message 402, @current_user.errors.full_messages.first
    end
  end

  def logout
    @current_user.update(last_sign_in_at: DateTime.current)
    @device = Device.and({device_token: params[:device][:device_token]}, {:user_id => @current_user.id})
    render_message 200, "Logged out successfully." if @device.destroy_all  
  end

  def send_otp_mobile
    @mobile = params[:mobile]
    @mobile_code = params[:code]
    @user = User.where(:id.ne => @current_user.id).where(:mobile => @mobile)
    return render json: {responseCode: 402, responseMessage: "Mobile no already exist."} if @user.present?
    User.generate_otp_and_send(@mobile, @mobile_code, @current_user)
    @merge = @current_user.as_json.merge("new_mobile" => @mobile, "new_code" => @mobile_code).except("otp", "otp_gen_time", "unique_id")
    return render json: {responseCode: 200, responseMessage: "OTP send to your no.", user: @merge}
  end

  def otp_change_mobile
    if @current_user.otp == params[:otp]
      if @current_user.otp_expired?
        return render_message 402, "OTP is expired."
      else
        @current_user.update_attributes(mobile: params[:mobile], code: params[:code], otp: nil)
        render :json =>  {:responseCode => 200, :responseMessage => "Mobile no. change successfully."}
      end
    else
      return render_message 402, "OTP is not valid."
    end
  end

  def forgot_password
    if params[:mobile].present?
      @user = User.find_by({mobile: params[:mobile]})
      return render_message 402, "User doesn't exists." unless @user.present?
      User.generate_otp_and_send(@user.mobile, @user.code, @user)
      render json: {responseCode: 200, responseMessage: "SMS has been sent with new otp.", user: @user.as_json.slice("mobile", "email")}
    elsif params[:email].present?
      @user = User.find_by({email: params[:email]})
      return render_message 402, "User doesn't exists." unless @user.present?
      User.generate_otp_and_send_mailer(@user)
      render json: {responseCode: 200, responseMessage: "Mail has been sent with new otp.", user: @user.as_json.slice("mobile", "email")}
    else
      {responseCode: 402, responseMessage: "Please provide mobile no or email."}
    end
  end

  def update_password
    @user = User.find_by({mobile: params[:mobile]})
    return render_message 402, "User doesn't exist." unless @user.present?
    if @user.update_attributes(password: params[:password])
       @select = @user.as_json.merge("image" => @user.try(:image).try(:file_url)).except("otp", "otp_gen_time", "unique_id")
       render json: {responseCode: 200, responseMessage: "Profile updated successfully.",user: @select}
    else
      render_message 402, @user.errors.full_messages.first
    end
  end

  def upload_doc
    user_doc = @current_user.user_docs.new(module_type: params[:module_type], doc_no: params[:doc_no], doc_type: params[:doc_type], front_img: params[:front_img], back_img: params[:back_img])
    if user_doc.save
      render :json =>  {:responseCode => 200, :responseMessage => "Document uploaded successfully."}
    else
      return render_message 402, user_doc.errors.full_messages.first
    end
  end

  private

  def user_params
    params.permit(:email, :password, :name, :dob, :code, :mobile, :gender, :address, :unique_id, :touch_id)
  end

  def update_user_params
    params.permit(:email, :password, :name, :dob, :gender, :address, :touch_id)
  end

  def device_params
    params.require(:device).permit(:device_type, :device_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC-lQ-u7das4d7DuTcjLii2G89FB2FqO-I&sensor=false&libraries=places"></script>
<div class="content-wrapper">
  <section class="main-block">
    <div class="container">
      <div class="row">
        <div class="tab-content">
  				<div class="tab-pane fade active in" id="default-tab-1">
  					<div class="tab-pane">
  							<%= form_for [:admin, @user],html: {id: "new_user"} do |f|%>
  								<div class="detail-form m-t-40 m-b-40">

  									<div class="form-group">
  										<div class="row">
  											<label class="col-sm-4 col-md-3 control-label">User Name</label>
  											<div class="col-sm-8 col-md-7">
  											  <%= f.text_field :name, class: "form-control", required: true, placeholder: ""%>
  											</div>
  										</div>
  									</div>
                    
                    <div class="form-group">
                      <div class="row">
                        <label class="col-sm-4 col-md-3 control-label">Email</label>
                        <div class="col-sm-8 col-md-7">
                          <%= f.email_field :email, class: "form-control", required: true, placeholder: ""%>
                        </div>
                      </div>
                    </div>

                    <div class="form-group">
  										<div class="row">
  											<label class="col-sm-4 col-md-3 control-label">Mobile</label>
  											<div class="col-sm-8 col-md-7">
  											  <%= f.text_field :mobile, class: "form-control", required: true, placeholder: ""%>
  											</div>
  										</div>
  									</div>

                    <div class="form-group">
  										<div class="row">
  											<label class="col-sm-4 col-md-3 control-label">Date of Birth</label>
  											<div class="col-sm-8 col-md-7">
  											  <%= f.text_field :dob, class: "form-control", required: true, :id=>'userdatetimepicker1', value: (f.object.dob.to_date.strftime("%d/%m/%Y") rescue "")%>
  											</div>
  										</div>
  									</div>
                    
  									<div class="form-group">
  										<div class="row">
  											<label class="col-sm-4 col-md-3 control-label">Address</label>
  											<div class="col-sm-8 col-md-7">
  											  <%= f.text_field :address, class: "form-control", placeholder: "", required: true%>
  											</div>
  										</div>
  									</div>

  									<div class="form-group">
  										<div class="text-center attendee-cent-s">
  											<button class="btn btn-default btn-green" type="submit">Submit</button>
  										</div>
									</div>
								</div>
							<%end%>
						</div>
  				</div>
        </div>
      </div>
    </div>
  </section>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $('#userdatetimepicker1').datetimepicker({
      format: 'DD/MM/YYYY',
      useCurrent: false,
      maxDate: new Date()
    });
    window.onload = function() {
      var myInput = document.getElementById('userdatetimepicker1');
      myInput.onpaste = function(e) {
        e.preventDefault();
      }
    }
  });
</script>

app/views/admin/users/edit.html.erb
<%= render :partial => "form"%>

app/views/admin/users/index.html.erb
 <h1 class="heading">USER MANAGEMENT</h1>
 <div class="filter-block">
 <fieldset class="global-fieldset">
    <legend>Filter By</legend>
    <div class="filter-content user-filter">
    <%= form_tag admin_users_path, method: :get do  %>
      <div class="row">
      <div class="col-sm-3">
          <div class="user-label">                              
           <div class="">
            <%= text_field_tag :search ,"", class: 'form-control custom-control1', placeholder: 'Search by Name or Email', value: "#{params[:search]}"  %>
           </div>                            
         </div>
       </div> 
         <div class="col-sm-3">
          <div class="user-label">
            <div class="">
              <%=  select_tag :status,options_for_select([["All",""],["Active","1"],["Blocked","0"]]), class:"form-control custom-control1" %>
          </div>
          </div>
        </div> 
        <div class="col-sm-3">
          <div class="user-label">
            <div class="">
              <%=  select_tag :gender,options_for_select([["All",""],["Male","0"],["Female","1"]]), class:"form-control custom-control1" %>
          </div>
          </div>
      </div>
       <div class="col-sm-3">
        <div class="text-left">
          <button class="btn btn-red">Search</button>
        </div>
      </div>
    </div>
    <%end%>
  </div>
</fieldset>
</div>

<div class="box box-blue">
  <div class="box-body">
    <div class="custom-table table-responsive">
      <table class="table table-striped table-border">
        <thead>
          <tr>
            <th>User Image</th>
            <th>User Name</th>                            
            <th>Email </th>
            <th>Phone Number </th>
            <th>Gender </th>
            <th>Last Logged in </th>                                                        
            <th>Action</th>
          </tr>
        </thead>
        <center>
        </center>
        <% @users.each do |user| %>
        <% unless user.eql?(nil) %>
        <tbody>
          <tr>
          <td><%= user.image.present? ? image_tag(user.image.try(:file_url),:width => 50, :height => 50, :class => 'news-content') : image_tag("/1.png",:width => 50, :height => 50, :class => 'news-content') %></td>
            <td><%= truncate(user.try(:name), omision: "...", length: 30) %></td>
            <td><%= truncate(user.try(:email), omision: "...", length: 30) %></td>
            <td><%= truncate(user.try(:mobile), omision: "...", length: 30) %></td> 
            <%if user.gender == "0" %>
              <td><%= "Male" %></td> 
            <%elsif user.gender == "1" %>
              <td><%= "Female" %></td>
              <%else%>
              <td><%= "NA"%></td>
            <%end%>
            <td><%= user.last_sign_in_at ? user.last_sign_in_at.try(:localtime).try(:strftime, "%d %B, %Y %I:%M %p") : "N/A" %></td>                   
  
                             
            <td>
              <div class="action-btn">
                <%#if user.status.eql?(1) || user.verified? %>
                <%#= link_to '<i class="fa fa-ban" aria-hidden="true"></i> Block'.html_safe,user_status_admin_users_path(:id => user.id), method: :post,:class=>"btn btn-sm btn-danger",:data => { :confirm => "Are you sure to block this user?" }%>
                <%#elsif user.status.eql?(2) || user.blocked? %>
                <%#= link_to '<i class="fa fa-check" aria-hidden="true"></i> Unblock'.html_safe,user_status_admin_users_path(:id => user.id), method: :post,:class=>"btn btn-sm btn-primary",:data => { :confirm => "Are you sure to activate this user?" }%>
                <%#end%>    
                
                  <%= link_to '<i class="fa fa-eye" aria-hidden="true"></i> View'.html_safe, admin_user_path(id: user.id), :class=>"btn btn-sm btn-success width90"%>
                  <%if user.status == 0 %>
                  <%= link_to '<i class="fa fa-check-square-o" aria-hidden="true"></i> Unblock'.html_safe, user_status_admin_users_path(id: user.id, status: 1), :class=>"btn btn-sm btn-primary width90" , :data => { :confirm => "Are you sure to activate this user?" }%>
                  <%elsif user.status == 1 %>
                  <%= link_to '<i class="fa fa-ban" aria-hidden="true"></i> Block'.html_safe, user_status_admin_users_path(id: user.id, status: 0), :class=>"btn btn-sm btn-danger width90", :data => { :confirm => "Are you sure to deactivate this user?" }%>
                  <%else %>
                  <%= link_to '<i class="fa fa-ban" aria-hidden="true"></i> Not Verify'.html_safe, "#", :class=>"btn btn-sm btn-warning width90"%>  
                  <%end%>
                  <%= link_to '<i class="fa fa-trash" aria-hidden="true"></i> Delete'.html_safe,  admin_user_path(user.id), method: :delete,:class=>"btn btn-sm btn-danger width90", data: {confirm: 'Are you sure to delete this user?' }%>
              </div>  
            </td>
          </tr>                                
        </tbody>
        <%end%>
        <%end%>
      </table>
        <%= "No user found." unless @users.present?%>
    </div>                     
  </div>
</div>

<div class="custom-pagination">
  <%= will_paginate @users %>
</div>

</div>
</div>
</div>

app/views/admin/users/new.html.erb
<%= render :partial => "form"%>

app/views/admin/users/show.html.erb
<div class="right-inner">
<center>
<h1 class="heading"> USER DETAILS</h1>
</center>
  <div class="form-show-body width600">
      <form>
        <div class="form-group">
          <div class="row">
            <label class="col-sm-2"> Name </label>
            <div class="col-sm-8">
               <%= @user.try(:name) %>
            </div>
          </div>
        </div>
       
        <div class="form-group">
          <div class="row">
            <label class="col-sm-2"> Email  </label>
            <div class="col-sm-8">
              <%= @user.try(:email) %>
            </div>
          </div>
        </div>
       
        <div class="form-group">
          <div class="row">
            <label class="col-sm-2">Mobile Number  </label>
            <div class="col-sm-8">
              <%= @user.try(:mobile) %>
          </div>
        </div>
        </div>
        
        <div class="form-group">
          <div class="row">
            <label class="col-sm-2">Date of Birth </label>
            <div class="col-sm-8">
                <%= @user.try(:dob) %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <label class="col-sm-2">Gender </label>
            <div class="col-sm-8">
                <%= @user.try(:gender).eql?("0") ? "Male" : "Female" %>
            </div>
          </div>
        </div>


        
        <div class="update-btn text-center">
          <%= link_to 'BACK', admin_users_path, class: "btn btn-red btn-common" %>   
        </div>
      </form>
    </div>

</div>  


  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#slider-range" ).slider({
      range: true,
      min: 0,
      max: 500,
      values: [ '<%= @user&.min_behaviour %>', '<%= @user&.max_behaviour %>' ],
      slide: function( event, ui ) {
        $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
      }
    });
    $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
      " - $" + $( "#slider-range" ).slider( "values", 1 ) );
  } );

  $('#slider-range').slider({ disabled: true });
  </script>